ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.sagenotes.gateway.SerializationKt.configureSerialization
      - ru.sagenotes.gateway.WebsocketsKt.configureWebsockets
      - ru.sagenotes.gateway.RoutingKt.configureRouting
