ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.sagenotes.notificationservice.SerializationKt.configureSerialization
      - ru.sagenotes.notificationservice.RabbitmqKt.configureRabbitmq
      - ru.sagenotes.notificationservice.WebsocketsKt.configureWebsockets
      - ru.sagenotes.notificationservice.RoutingKt.configureRouting
